# Generated by Django 6.0.4 on 2026-04-10 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platita', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_objetivo', models.IntegerField()),
                ('monto_actual', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('FIJO', 'Gasto Permanente (Mensual)'), ('MES', 'Gasto del Mes (Variable)')], default='MES', max_length=10),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_base', models.IntegerField(default=0)),
                ('horas_extras', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
