# Generated by Django 6.0.4 on 2026-04-10 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platita', '0002_metaahorro_remove_gasto_categoria_gasto_tipo_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('ALIMENTACION', 'Alimentación'), ('TRANSPORTE', 'Transporte'), ('ENTRETENCION', 'Entretenimiento'), ('SERVICIOS', 'Servicios/Luz/Agua'), ('OTROS', 'Otros')], default='OTROS', max_length=20),
        ),
        migrations.AddField(
            model_name='metaahorro',
            name='icono',
            field=models.CharField(default='bi-piggy-bank', max_length=50),
        ),
        migrations.AddField(
            model_name='metaahorro',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='color_perfil',
            field=models.CharField(default='#00bfa5', max_length=7),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('MES', 'Gasto del Mes'), ('FIJO', 'Gasto Fijo Mensual'), ('FUTURO', 'Gasto Próximo/Planificado')], default='MES', max_length=10),
        ),
    ]
