# Generated by Django 6.0.4 on 2026-04-10 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platita', '0003_gasto_categoria_metaahorro_icono_metaahorro_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Hogar', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='metaahorro',
            name='usuario',
        ),
        migrations.AddField(
            model_name='gasto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gasto',
            name='hogar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='platita.hogar'),
        ),
        migrations.AddField(
            model_name='metaahorro',
            name='hogar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='platita.hogar'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='hogar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrantes', to='platita.hogar'),
        ),
    ]
