# Generated by Django 6.0.4 on 2026-04-10 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platita', '0004_hogar_remove_gasto_usuario_remove_metaahorro_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_sueldos', to='platita.perfil')),
            ],
            options={
                'unique_together': {('perfil', 'mes', 'anio')},
            },
        ),
    ]
