# Generated by Django 6.0.4 on 2026-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platita', '0005_registrosueldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='horas_extras',
        ),
        migrations.AlterField(
            model_name='registrosueldo',
            name='horas_extras',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrosueldo',
            name='sueldo_base',
            field=models.IntegerField(),
        ),
    ]
