# Generated by Django 6.0.4 on 2026-04-10 20:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platita', '0006_remove_perfil_horas_extras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AddField(
            model_name='gasto',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('ALIMENTACION', '🍎 Alimentación'), ('TRANSPORTE', '🚌 Transporte'), ('ENTRETENCION', '🎮 Entretenimiento'), ('SERVICIOS', '💡 Servicios/Luz/Agua'), ('ESTUDIOS', '📚 Estudios/PC'), ('OTROS', '✨ Otros')], default='OTROS', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_gastos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='hogar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='platita.hogar'),
            preserve_default=False,
        ),
    ]
