# Generated by Django 6.0.4 on 2026-04-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platita', '0007_alter_gasto_options_gasto_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('ALIMENTACION', '🍎 Alimentación'), ('TRANSPORTE', '🚌 Transporte'), ('ENTRETENCION', '🎮 Entretenimiento'), ('SERVICIOS', '💡 Servicios/Luz/Agua'), ('ESTUDIOS', '📚 Estudios/PC'), ('HOGAR', '🏠 Hogar/Muebles'), ('OTROS', '✨ Otros')], default='OTROS', max_length=20),
        ),
    ]
