# Generated by Django 6.0.4 on 2026-04-11 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platita', '0008_alter_gasto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('tipo', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='platita.metaahorro')),
            ],
        ),
    ]
