# Generated by Django 6.0.4 on 2026-04-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platita', '0009_movimientoahorro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('MES', 'Gasto del Mes'), ('FIJO', 'Gasto Fijo Mensual')], default='MES', max_length=10),
        ),
    ]
