# Generated by Django 6.0.4 on 2026-04-12 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platita', '0010_alter_gasto_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoahorro',
            name='meta',
        ),
        migrations.CreateModel(
            name='CompraAlimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.IntegerField()),
                ('tarjeta', models.CharField(choices=[('AMIPASS', '💳 Amipass'), ('JUNAEB_R', '🟢 Junaeb Renato'), ('JUNAEB_B', '🟣 Junaeb Belén')], max_length=20)),
                ('fecha', models.DateField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platita.hogar')),
            ],
            options={
                'verbose_name': 'Compra Alimentación',
                'verbose_name_plural': 'Compras Alimentación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='MetaAhorro',
        ),
        migrations.DeleteModel(
            name='MovimientoAhorro',
        ),
    ]
