# Generated by Django 6.0.4 on 2026-04-12 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platita', '0011_remove_movimientoahorro_meta_compraalimentacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraalimentacion',
            name='hogar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_alimentacion', to='platita.hogar'),
        ),
        migrations.CreateModel(
            name='CargaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('monto_amipass', models.IntegerField(default=80000)),
                ('monto_junaeb_renato', models.IntegerField(default=48000)),
                ('monto_junaeb_belen', models.IntegerField(default=48000)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_mensuales', to='platita.hogar')),
            ],
            options={
                'verbose_name': 'Carga Mensual',
                'verbose_name_plural': 'Cargas Mensuales',
                'unique_together': {('hogar', 'mes', 'anio')},
            },
        ),
    ]
