# Generated by Django 6.0.4 on 2026-04-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platita', '0012_alter_compraalimentacion_hogar_cargamensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraalimentacion',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='compraalimentacion',
            name='precio_unitario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compraalimentacion',
            name='monto',
            field=models.IntegerField(editable=False),
        ),
    ]
