# Generated by Django 6.0.4 on 2026-04-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platita', '0015_tareamaestra_tareaasignada_delete_tareasemanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaasignada',
            name='nombre_manual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
