# Generated by Django 6.0.4 on 2026-04-12 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platita', '0016_tareaasignada_nombre_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaasignada',
            name='tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='platita.tareamaestra'),
        ),
    ]
